const { GoogleGenAI } = require("@google/genai");

const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY,
});


const generatePlayerComparison = async (players) => {
  try {
    if (!Array.isArray(players) || players.length < 2) {
      throw new Error(
        "At least 2 players are required for AI comparison"
      );
    }


    const comparisonData = players.map((player) => ({
      rank: player.rank,

      player: {
        name: player.player.name,
        role: player.player.role,
        age: player.player.age,
      },

      features: {
        matches: player.features.matches,
        totalRuns: player.features.totalRuns,
        battingAverage: player.features.battingAverage,
        strikeRate: player.features.strikeRate,
        fours: player.features.fours,
        sixes: player.features.sixes,
        totalWickets: player.features.totalWickets,
        economy: player.features.economy,
        recentForm: player.features.recentForm,
        consistency: player.features.consistency,
        battingImpact: player.features.battingImpact,
        bowlingImpact: player.features.bowlingImpact,
        powerHitting: player.features.powerHitting,
        overallImpact: player.features.overallImpact,
      },

      prediction: {
        potentialLevel:
          player.prediction.potentialLevel,
        potentialScore:
          player.prediction.potentialScore,
        prediction:
          player.prediction.prediction,
      },
    }));

    // ==========================================
    // Gemini Prompt
    // ==========================================

    const prompt = `


You are CricketIQ, an AI-powered cricket comparison analyst.

Your job is to compare multiple cricket players using ONLY
the structured data provided below.

The backend has already calculated all player statistics,
performance metrics, ML predictions, and rankings.

Your job is NOT to recalculate these values.

Your job is to explain the differences between the players
in a professional, objective, cricket-specific manner.

==================================================
PLAYER COMPARISON DATA
======================

${JSON.stringify(comparisonData, null, 2)}

==================================================
ANALYSIS RULES
==============

1. Use ONLY the information provided above.

2. NEVER invent:

   * career history
   * injuries
   * fitness information
   * opposition quality
   * rankings
   * team history
   * playing conditions
   * future performances
   * statistics not provided

3. Do NOT modify or recalculate any statistics.

4. Clearly distinguish between:

   * observed performance statistics
   * calculated CricketIQ metrics
   * ML prediction

5. Compare players using relevant statistics.

6. For BATTERS, focus primarily on:

   * total runs
   * batting average
   * strike rate
   * boundaries
   * power hitting
   * recent form
   * consistency
   * batting impact

7. For BOWLERS, focus primarily on:

   * wickets
   * economy
   * runs conceded
   * recent form
   * consistency
   * bowling impact

8. For ALL-ROUNDERS, consider both batting and bowling.

9. Do not treat a statistic as a weakness when it is
   irrelevant to the player's role.

10. Consider sample size carefully.

11. A player with only one or two matches may have
    unstable performance metrics.

12. Do not assume that the player with the highest
    ML potential score is automatically the best player
    in every situation.

13. The ML prediction is a predictive signal,
    NOT a guarantee of future success.

14. When discussing rankings, remember that the ranking
    was generated by the backend using ML potential score.

15. Recommendations must be based only on the provided data.

16. Do not exaggerate differences between players when
    the available data is limited.

==================================================
OUTPUT REQUIREMENTS
===================

Return ONLY valid JSON.

Do not include Markdown.
Do not include code fences.
Do not include additional text.

Use exactly this structure:

{
"overallComparison": "Overall comparison of the players based on the available evidence.",

"playerAdvantages": [
{
"player": "Player name",
"advantages": [
"Specific advantage supported by the data.",
"Another specific advantage."
]
}
],

"categoryComparison": [
{
"category": "Category name",
"leader": "Player name",
"explanation": "Explain why this player leads this category using the provided statistics."
}
],

"potentialComparison": "Explain how the ML potential scores and levels compare.",

"sampleSizeAssessment": "Explain how differences in the number of matches affect the reliability of the comparison.",

"recommendation": "Provide a practical recommendation based only on the available evidence.",

"confidence": "LOW"
}

The confidence field must be exactly:

LOW
MEDIUM
HIGH

Use:

LOW:
Very limited data or major differences in sample size.

MEDIUM:
Reasonable data exists but additional matches would improve
the reliability of the comparison.

HIGH:
Sufficient and relatively balanced performance data exists.

Remember:

* Use only provided information.
* Do not invent facts.
* Do not recalculate metrics.
* Do not guarantee future performance.
* Respect player roles.
* Consider sample size.
* Keep the comparison professional and cricket-specific.
  `;

    const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: prompt,
    });


    const text = response.text.trim();

    const cleanedText = text
      .replace(/^`json\s*/i, "")
      .replace(/^`\s*/i, "")
      .replace(/\s*```$/i, "")
      .trim();

    return JSON.parse(cleanedText);

  } catch (error) {
    console.error(
      "Gemini AI Comparison Service Error:",
      error.response?.data || error.message
    );

    throw new Error(
      "Unable to generate AI player comparison"
    );
  }
};

module.exports = {
  generatePlayerComparison,
};
